### ISSUE TITLE
about requirejs.yml

### ISSUE THREAD

**Issue by smapsekar** [jwhitley/requirejs-rails#100]
is there a better way to write this ?

```
shim:
  jquery.rails:
    deps: ["jquery"]
  jquery.ui:
    deps: ["jquery"]
  jquery.clickoutside:
    deps: ["jquery"]
  jquery.cookie:
    deps: ["jquery"]
  jquery.countdown:
    deps: ["jquery"]
  jquery.fancybox:
    deps: ["jquery"]
  jquery.flexslider:
    deps: ["jquery"]
  jquery.isotope:
    deps: ["jquery"]
  jquery.jscrollpane:
    deps: ["jquery"]
  jquery.scrollable:
    deps: ["jquery"]
  jquery.timeago:
    deps: ["jquery"]
  jquery.typeahead:
    deps: ["jquery"]
  jquery.validate:
    deps: ["jquery"]
  jquery.waypoints:
    deps: ["jquery"]
  jquery.colorpicker:
    deps: ["jquery"]
  jquery.tools:
    deps: ["jquery"]
  jquery.spin:
    deps: ["jquery"]
  jquery.query:
    deps: ["jquery"]
  jquery.recurly:
    deps: ["jquery"]
  jquery.mousewheel:
    deps: ["jquery"]
  jquery.jcountdown:
    deps: ["jquery"]
  jquery.masonry:
    deps: ["jquery"]
  jquery.debounce:
    deps: ["jquery"]
  jquery.color:
    deps: ["jquery"]
  numberformatter:
    deps: ["jshashtable"]
  search:
    deps: ["jquery.typeahead"]
```
