### ISSUE TITLE
Fingerprinted image not being referenced from precompiled CSS

### ISSUE THREAD

**Issue by prashaantt** [jwhitley/requirejs-rails#170]
In production, a style like

``` css
body {
  background-image: image-url('image.png');
}
```

is getting fingerprinted (there's an output like `image-xxxxx.png`) but it's not being referenced back from the CSS to make it work, so the CSS still uses the raw image name and fails to load it:

``` css
body {
  background-image: url('image.png');
}
```
