### ISSUE TITLE
Misunderstanding about `modules` in requirejs.yml

### ISSUE THREAD

**Issue by StevenLangbroek** [jwhitley/requirejs-rails#190]
I think I'm misunderstanding the `modules` node in `requirejs.yml`. The documentation says:

> Pulled in via a dynamic require() call. Modules which are solely referenced by a dynamic require() call (i.e. a call not optimized by r.js) must be specified in the modules section in order to produce a correct build.

I've added a couple of modules in our requirejs.yml, like so:

``` yml
modules:
  - name: 'main'
  - name: 'dash/dash'
  - name: 'page_controllers/applications'
  - name: 'page_controllers/category_blacklists'
  - name: 'page_controllers/companies'
  - name: 'page_controllers/mediations'
  - name: 'page_controllers/offer_filters'
```

However, when i set `RAILS_ENV=production`, and run `$ bundle exec rake assets:precompile`, they do not get compiled. The only file that gets optimised by `r.js` seems to be the `main` module. The page_controller modules are dynamically called in main.js, but those calls fail as they're not in `public/assets`. Any thoughts as to what's going on here?
