### ISSUE TITLE
config not passed to r.js

### ISSUE THREAD

**Issue by Rush** [jwhitley/requirejs-rails#197]
I have set up a shim config for my application in `config/requirejs.yml`, such as:
```YAML
shim: 
  jquery:
    exports: 'jQuery'
  jquery_ujs:
    deps: ['jquery']
  'bootstrap': ['jquery', 'jquery_ujs']
  'twitter/bootstrap/rails/confirm':
    deps: ['bootstrap', 'jquery_ujs']
  'novnc/rfb':
    deps: ["novnc/util","novnc/webutil", "novnc/base64", "novnc/websock", "novnc/des",
        "novnc/keysymdef", "novnc/keyboard", "novnc/input", "novnc/display", "novnc/jsunzip"]
  'novnc':
    deps: ['novnc/rfb']
    exports: 'RFB'
modules:
  - name: 'application'
wrapShim: true
```

but I am not seeing those options passed to r.js, file `tmp/requirejs/rjs_driver.js` contains:

```YAML
var requirejs = require("/home/rush/.rvm/gems/ruby-2.1.3/gems/requirejs-rails-0.9.5/bin/r.js")
var baseConfig = {
  "baseUrl": "/home/rush/virtkick/webapp/tmp/requirejs/src",
  "dir": "/home/rush/virtkick/webapp/tmp/requirejs/dst"
};

baseConfig.modules = [
  {
  "name": "application"
},
];
```

What is wrong, is this application bug? How can I make the build_config to be loaded?
