### ISSUE TITLE
Paths don't loaded when Rails server started as development

### ISSUE THREAD

**Issue by lancedikson** [jwhitley/requirejs-rails#212]
Hi! So, I have a problem: paths from requirejs.yml do not loaded when I start Rails server and dependencies do not resolve. I use Bower as package manager for my project and all third-party files are locate at `vendor/assets/bower`. They are available for Assets Pipeline — I made sure about it.
So, I have this `requirejs.yml`:

```
paths:
  jquery: "jquery/dist/jquery"
  foundation: "foundation/js/foundation"
  modernizr: "modernizr/modernizr"
  app: "js/application"
shim:
  foundation:
    deps: ['jquery', 'modernizr']
optimize: 'none'
modules:
  - name: 'common'
    include: ['jquery', 'foundation', 'modernizr']
  - name: 'application'
    exclude: ['common']
  - name: 'admin/app'
    exclude: ['common']
priority: ['common']
```

My common file is empty. Whether it should contain any code? In the official Require's [example-multipage-shim](https://github.com/requirejs/example-multipage-shim/blob/master/www/js/common.js) common include require.config(). Should I do something like this?

So, I have the next code loaded at page with the `requirejs.yml` above:
```
<script src="/assets/require-4bbd1abb9811b646f2aea5d348d28770.js"></script><script>require.config({"baseUrl":"/assets","paths":{"common":"/assets/common-64e62ddc273c2f5847f30d698ca14b67","application":"/assets/application-4f1870d7adc38f35ff024c98eb5b71a4","admin/app":"/assets/admin/app-4f1870d7adc38f35ff024c98eb5b71a4"},"priority":["common"],"shim":{"foundation":{"deps":["jquery","modernizr"]}}}); require(["admin/app"]);</script>
```

Paths do not include paths that defined at `requirejs.yml`. How I can fix it? Maybe I do something wrong. Give me advice please, if that is it.
