### ISSUE TITLE
Engine assets not picked up by default for r.js optimization?

### ISSUE THREAD

**Issue by drakes** [jwhitley/requirejs-rails#220]
I ran into trouble trying to precompile assets for an app with a custom engine (I'm guessing unrelated to #200, no crash). Initially my `requirejs.yml` looked like:

```
paths:
  mithril: 'mithril/mithril'
  amplify: 'amplify/lib/amplify.core'
shim:
  amplify:
    exports: 'amplify'
```

The scripts for the engine were not being optimized by r.js; I managed to fix that by adding a modules section which explicitly referred to the top-level module of the engine:

```
modules:
  - name: 'application'
  - name: 'vbc/application'
paths:
  mithril: 'mithril/mithril'
  amplify: 'amplify/lib/amplify.core'
shim:
  amplify:
    exports: 'amplify'
```

It's unclear to me whether this is expected behavior (maybe could be mentioned in the docs), or if there's something else I should be doing to point requirejs-rails to my engine (everything worked fine in development).
