### ISSUE TITLE
Precompilation fails with "module path does not exist" after upgrading to 0.9.5

### ISSUE THREAD

**Issue by agis-** [jwhitley/requirejs-rails#236]
Hello.

I'm on a Rails 3.2.22 application and using requirejs-rails 0.9.0 for a long time everything is fine. However, after upgrading to 0.9.5, I get the following error while deploying:

```shell
#...
rake aborted!
Asset compilation with node failed with error:

{ [Error: Error: ERROR: module path does not exist: /home/staging/tmp/assets/rjs/application_desktop.js for module named: application_desktop. Path is relative to: /home/staging
    at /home/bundles/staging/ruby/1.9.1/gems/requirejs-rails-0.9.8/bin/r.js:27089:35
]
  originalError: [Error: ERROR: module path does not exist: /home/staging/tmp/assets/rjs/application_desktop.js for module named: application_desktop. Path is relative to: /home/staging] }

/home/bundles/staging/ruby/1.9.1/gems/requirejs-rails-0.9.8/lib/tasks/requirejs-rails_tasks.rake:141:in `block (3 levels) in <top (required)>'
Tasks: TOP => requirejs:precompile:all => requirejs:precompile:run_rjs
(See full trace by running task with --trace)
rake aborted!
Command failed with status (1): [/usr/bin/ruby1.9.1 /home/bundles...]
/home/bundles/staging/ruby/1.9.1/gems/requirejs-rails-0.9.8/lib/tasks/requirejs-rails_tasks.rake:18:in `ruby_rake_task'
/home/bundles/staging/ruby/1.9.1/gems/requirejs-rails-0.9.8/lib/tasks/requirejs-rails_tasks.rake:85:in `block (3 levels) in <top (required)>'
Tasks: TOP => assets:precompile => requirejs:precompile:external
(See full trace by running task with --trace)
```

Here are the relevant parts from `requirejs.yml`:

```yaml
# config/requirejs.yml

locale : 'en'
optimize : 'none'
paths:
  jquery.datepicker:  'vendor/jquery/plugins/jquery.datepicker'
  jquery.jcrop:       'vendor/jquery/plugins/jquery.jcrop'
modules :
  - name: 'application_desktop'

  - name: 'application_tablet'

  - name: 'application_mobile'
```

The file in question is located at `app/asets/javascripts/rjs/application_desktop.js.coffee`.

Note that I also have the following initializer:

```ruby
# config/initializers/requirejs_path_override.rb

# Override the baseUrl value used in the build_config parameter to
# locate the temporary folder where compiled scripts put (from coffeescript compiler)
# This workaround is only needed for usage with r.js driver of requirejs-rails gem
if ENV['RAILS_GROUPS'] == "assets"
  requirejs = Rails.application.config.requirejs
  requirejs.build_config['baseUrl'] = "#{Rails.root}/tmp/assets/rjs"
end
```

Note that compilation is fine with 0.9.0, 0.9.1 and 0.9.2. Also, it fails with the same error in 0.9.8.

Thanks.
