### ISSUE TITLE
Emit warning/error if baseUrl specified in config

### ISSUE THREAD

**Issue by olivernn** [jwhitley/requirejs-rails#44]
I'm trying to use require.js with rails 3.2 on heroku.  I'm having difficulty because the precompilation step is failing on heroku, it is also failing locally with the following error:

```
Error: ERROR: module path does not exist: /assets/lookup.js for module named: lookup
```

Currently I have an application called lookup.js and my app/assets/javascripts dir looks like this:

```
app/assets/javascripts/
├── lookup.js
├── models
│   └── car.js
└── views
    └── car_details_view.js
```

And in my requirejs.yml looks like this

```
modules:
  - name: lookup
baseUrl: /assets
paths:
  models: models
  views: views
```

Any ideas what I'm doing wrong?
