### ISSUE TITLE
Support use.js

### ISSUE THREAD

**Issue by jbasdf** [jwhitley/requirejs-rails#49]
I need to be sure that jquery is loaded for jquery_ujs to work properly. I'm using the configuration below:

``` yaml
modules: 
  - name: 'application' 
paths: 
  use: "use" 
use: 
  jquery_ujs: 
    deps: ["jquery"] 
```

However, I just get the following error:

Uncaught TypeError: Module 'jquery_ujs' is undefined or does not have a `use` config. Make sure it exists, add a `use` config, or don't use use! on it 

requirejs-rails has a whitelist that looks like this which filters out the use configuration: 

``` ruby
  self.run_config_whitelist = %w{ 
        baseUrl 
        callback 
        catchError 
        context 
        deps 
        jQuery 
        locale 
        packages 
        paths 
        priority 
        scriptType 
        urlArgs 
        waitSeconds 
        xhtml 
      } 
```

Since use.js is very useful for loading javascript that does not natively support AMD I propose that we include use in the list and add some documentation in the readme on how to use it.
