### ISSUE TITLE
Google maps doesn't get loaded :(

### ISSUE THREAD

**Issue by fourcolors** [jwhitley/requirejs-rails#71]
Hi I have something like this in my requirejs.yml and it works in development. 

``` yml

paths:
  twitter_bootstrap: 'shared/twitter_bootstrap'
  async: 'requirejs-plugins/src/async'
  datepicker: 'jquery-plugins/bootstrap-datepicker'

shim: 
  'gmap3':
    deps: ['jquery', 'async!http://maps.googleapis.com/maps/api/js?sensor=true']
    exports: '$.gmap3'

  'twitter/bootstrap': 
    deps: ['jquery']
    exports: '$.bootstrap'

  'jquery-plugins/jquery-autocomplete': 
    deps: ['jquery'] 
    exports: '$.autocomplete'

  'datepicker': 
    deps: ['jquery', 'twitter_bootstrap'] 
    exports: '$.datepicker'

```

However when I run my site by precompiling assets on heroku (staging) I get google is not defined. For some reason the google map isn't defined? How can I use google maps?
