### ISSUE TITLE
Assets folder alias issue

### ISSUE THREAD

**Issue by avaranovich** [jwhitley/requirejs-rails#81]
I am trying to "selectively" get the js files into requirejs.

they are located in the assets/javascripts/lib
and assets/javascripts/lib/dependencies

here is my require.yml config

```
paths:
 underscore: 'lib/dependencies/underscore'
 backbone: 'lib/dependencies/backbone'
 marionette: 'lib/dependencies/backbone.marionette'
 geppetto: 'lib/geppetto'
```

however, they are not compiled in the production mode. While they are served OK in the dev mode.

If I add the following

```
modules:
 - name: 'lib/dependencies/underscore'
 - name: 'lib/dependencies/backbone'
 - name: 'lib/dependencies/backbone.marionette'
 - name: 'lib/geppetto
```

They are compiled, but the require variable on the page is strange:

```
 <script>var require = {"baseUrl":"/assets","paths":    {"lib/dependencies/underscore":"/assets/lib/dependencies/underscore-cd950c5d26d0c0defb3d54c85769f625", "lib/dependencies/backbone":"/assets/lib/dependencies/backbone-03a32fd5270318872a932da63d361a01", "lib/dependencies/backbone.marionette":"/assets/lib/dependencies/backbone.marionette-54697121ad976f6559ed8915ba24a8ef","lib/geppetto":"/assets/lib/geppetto-2eae748edc4f2248f77bf93db95daf8e"}};</script>
  <script  src="/assets/require-52c77a71cdb25defabf0e084426dcf2f.js"></script>
```

I want to preserve the original alias, e.g. like this;

underscore: '/assets/lib/dependencies/underscore-cd950c5d26d0c0defb3d54c85769f625'

and not 

"lib/dependencies/underscore":"/assets/lib/dependencies/underscore-cd950c5d26d0c0defb3d54c85769f625"

Any ideas what's going wrong?
