### ISSUE TITLE
Unable to use CDNs with almond.js

### ISSUE THREAD

**Issue by pboling** [jwhitley/requirejs-rails#96]
assets:precompile fails when using the following together:

`config/environments/production.rb`

```
  config.requirejs.loader = :almond
```

`config/requirejs.yml`

```
paths:
  domReady:
    - '//cdnjs.cloudflare.com/ajax/libs/require-domReady/2.0.1/domReady.js'
    - 'domReady'
  jquery:
    - '//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js'
    - '//cdnjs.cloudflare.com/ajax/libs/jquery/1.8.3/jquery.min.js'
    - '//ajax.aspnetcdn.com/ajax/jQuery/jquery-1.8.3.min.js'
    - 'jquery'
```
